//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaStreamer.Domain
{
    using System;
    
    public partial class Administrator : MediaEntity
    {
        public Guid AdministratorID { get; set; }
        public Nullable<Guid> ModeratorID { get; set; }
        public Nullable<Guid> UserID { get; set; }
        
        public virtual User User { get; set; }
        public virtual Moderator Moderator { get; set; }

        public override string GetId()
        {
            return AdministratorID.ToString();
        }

        public override bool IsValid()
        {
            return AdministratorID != Guid.Empty;
        }
    }
}
