//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaStreamer.Domain
{
    using System;
    using System.Collections.Generic;
#if NETCOREAPP || NET45 || NETSTANDARD
    using System.ComponentModel.DataAnnotations;
#endif

    public partial class ArtistGenre : MediaEntity
    {
        public Guid ArtistID { get; set; }
        public Guid GenreID { get; set; }

        public virtual Artist Artist { get; set; }
        public virtual Genre Genre { get; set; }

        public override string GetId()
        {
            return ArtistID.ToString() + ","+ GenreID.ToString();
        }

        public override bool IsValid()
        {
            return !(ArtistID == Guid.Empty) && (GenreID != Guid.Empty);
        }
    }
}