//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaStreamer.Domain
{
    using System;
    using System.Collections.Generic;
#if NETCOREAPP || NET45 || NETSTANDARD
    using System.ComponentModel.DataAnnotations;
#endif
    public partial class Genre
    {
        public Genre()
        {
            this.Albums = new HashSet<Album>();
            this.AlbumGenres = new HashSet<AlbumGenre>();
            this.ArtistGenres = new HashSet<ArtistGenre>();
        }

        public long GenreID { get; set; }

#if NETCOREAPP || NET45 || NETSTANDARD
        [StringLength(256)]
#endif
        public string GenreName { get; set; }
    
        public virtual ICollection<Album> Albums { get; set; }
        public virtual ICollection<AlbumGenre> AlbumGenres { get; set; }
        public virtual ICollection<ArtistGenre> ArtistGenres { get; set; }
    }
}
