//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaStreamer.Domain
{
    using MediaStreamer.Domain.Models;
    using System;
    using System.Collections.Generic;
#if NETCOREAPP || NET45 || NETSTANDARD
    using System.ComponentModel.DataAnnotations;
#endif
    public partial class Genre : MediaEntity
    {
        public Genre()
        {
            this.Albums = new HashSet<Album>();
            this.AlbumGenres = new HashSet<AlbumGenre>();
            this.ArtistGenres = new HashSet<ArtistGenre>();
        }

        public Guid GenreID { get; set; }

#if NETCOREAPP || NET45 || NETSTANDARD
        [StringLength(256)]
#endif
        public string GenreName { get; set; }
        public Guid? StyleId { get; set; }
        public Style Style { get; set; }
    
        public virtual ICollection<Album> Albums { get; set; }
        public virtual ICollection<AlbumGenre> AlbumGenres { get; set; }
        public virtual ICollection<ArtistGenre> ArtistGenres { get; set; }

        public override string GetId()
        {
            return GenreID.ToString();
        }

        public override bool IsValid()
        {
            return !string.IsNullOrEmpty(GenreName) && GenreName.Length >= 1;
        }
    }
}
