//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaStreamer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListenedComposition : ICompositionInstance
    {
        public System.DateTime ListenDate { get; set; }
        public Nullable<long> CountOfPlays { get; set; }
        public long UserID { get; set; }
        public Nullable<long> ArtistID { get; set; }
        public System.DateTime GroupFormationDate { get; set; }
        public Nullable<long> AlbumID { get; set; }
        public long CompositionID { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Artist Artist { get; set; }
        public virtual Composition Composition { get; set; }
        public virtual GroupMember GroupMember { get; set; }
        public virtual User User { get; set; }
        public string GetPath() {
            return Composition.FilePath;
        }
        public Composition GetInstance()
        {
            return Composition;
        }
    }
}
