//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaStreamer.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moderator : MediaEntity
    {
        public Moderator()
        {

        }
    
        public Guid ModeratorID { get; set; }
        public Nullable<Guid> UserID { get; set; }
        public virtual User User { get; set; }

        public override string GetId()
        {
            return ModeratorID.ToString();
        }

        public override bool IsValid()
        {
            return ModeratorID != Guid.Empty;
        }
    }
}
