//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaStreamer.Domain
{
    using System;
    using System.Collections.Generic;
#if NETCOREAPP || NET45 || NETSTANDARD
    using System.ComponentModel.DataAnnotations;
#endif

    public partial class Picture
    {
        public Guid PictureID { get; set; }
        public Nullable<Guid> XResolution { get; set; }
        public Nullable<Guid> YResolution { get; set; }
        public Nullable<Guid> SizeKb { get; set; }

#if NETCOREAPP || NET45 || NETSTANDARD
        [MaxLength(512)]
#endif
        public string FilePath { get; set; }
    }
}
