//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaStreamer.Domain
{
    using System;
    using System.Collections.Generic;
#if NETCOREAPP || NET45 || NETSTANDARD
    using System.ComponentModel.DataAnnotations;
#endif

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ListenedCompositions = new HashSet<ListenedComposition>();
        }
    
        public Guid UserID { get; set; }

#if NETCOREAPP || NET45 || NETSTANDARD
        [MaxLength(128)]
#endif
        public string UserName { get; set; }

#if NETCOREAPP || NET45 || NETSTANDARD
        [MaxLength(128)]
#endif
        public string Password { get; set; }

#if NETCOREAPP || NET45 || NETSTANDARD
        [MaxLength(256)]
#endif
        public string Email { get; set; }
        public System.DateTime DateOfSignUp { get; set; }

#if NETCOREAPP || NET45 || NETSTANDARD
        [MaxLength(256)]
#endif
        public string VKLink { get; set; }

#if NETCOREAPP || NET45 || NETSTANDARD
        [MaxLength(256)]
#endif
        public string FaceBookLink { get; set; }

#if NETCOREAPP || NET45 || NETSTANDARD
        [MaxLength(512)]
#endif
        public string Bio { get; set; }

#if NETCOREAPP || NET45 || NETSTANDARD
        [MaxLength(450)]
#endif
        public string AspNetUserId { get; set; }
    
        public virtual ICollection<ListenedComposition> ListenedCompositions { get; set; }
    }
}
